# Generated by Django 5.1.7 on 2025-05-26 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате: +375 (29) XXX-XX-XX.', regex='^\\\\+375\\\\s*\\\\(29\\\\)\\\\s*\\\\d{3}-\\\\d{2}-\\\\d{2}$')]),
        ),
    ]
