# Generated by Django 5.1.7 on 2025-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
