# Generated by Django 5.1.7 on 2025-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=500)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
