# Generated by Django 5.1.7 on 2025-05-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
    ]
