# Generated by Django 5.2.1 on 2025-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='requisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
