# Generated by Django 5.1.7 on 2025-05-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
