# Generated by Django 5.1.7 on 2025-05-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_product_default_price_productsupply_new_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceSubscription',
        ),
    ]
