# Generated by Django 5.1.7 on 2025-05-26 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_delete_pricesubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupply',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
