# Generated by Django 5.1.7 on 2025-05-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_productsupply_quantity_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
