# Generated by Django 5.1.7 on 2025-05-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_product_default_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
