# Generated by Django 5.1.7 on 2025-05-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_delete_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images/'),
        ),
    ]
