# Generated by Django 5.1.7 on 2025-05-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
