# Generated by Django 5.2.1 on 2025-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_remove_product_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/Not found image.png', null=True, upload_to='goods_images/'),
        ),
    ]
